int **createMatrix(int rows, int columns);
int **createGraph(int *n);
int degree(int i, int **matrix, int n);
void printMatrix(int **matrix, int rows, int columns);
void lacetes(int **matrix, int n);
void arestasMultiplas(int **matrix, int n);
void verticesIsolados(int **matrix, int n);
void verificaMaxV(int **matrix, int n);
void numArestas(int **matrix, int n);
void somatorioGraus(int **matrix, int n);
void numVertGrauImpar(int **matrix,int n);
void passeio(int **matrix, int n, int c);
void grafoRegular(int **matrix,int n);
void grafoSimples(int **matrix,int n);
void grafoCompleto(int **matrix,int n);
void saveGraph(int **matrix, int n);
int **removerArestas(int **matrix, int n);
int **removerVertice(int **matrix, int n, int indice);